---
deploymentMode: Monolithic

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: bank-eks-loki-logs-200174508136
      ruler: bank-eks-loki-logs-200174508136
      admin: bank-eks-loki-logs-200174508136
    s3:
      region: ap-south-1

serviceAccount:
  create: false
  name: loki

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: gp2
    size: 10Gi

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

minio:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

lokiCanary:
  enabled: true

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0
