apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: predictops-anomaly-alert
  namespace: monitoring
  labels:
    release: prometheus

spec:
  groups:
    - name: predictops.rules
      rules:
        - alert: PredictOpsHighAnomalyScore

          expr: |
            max by (namespace, target_service) (
              predictops_anomaly_score
            )
            >
            on(namespace, target_service)
            max by (namespace, target_service) (
              predictops_anomaly_threshold
            )

          for: 2m

          labels:
            severity: warning

          annotations:
            summary: "PredictOps alert: {{ $labels.target_service }}"
            description: >
              Anomaly detected in {{ $labels.target_service }}.
              Check Grafana, Loki and Tempo.